AllCops:
  TargetRubyVersion: 3.2.0
  NewCops: enable

Style/Documentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Metrics/ParameterLists:
  Max: 8

Metrics/AbcSize:
  Max: 30

# Style/Encoding:
#   Enabled: false

# Style/AsciiComments:
#   Enabled: false

# Style/HashEachMethods:
#   Enabled: true

# Style/HashTransformKeys:
#   Enabled: true

# Style/HashTransformValues:
#   Enabled: true

# Layout/LineLength:
#   Max: 120

# Layout/IndentationStyle:
#   Enabled: false

# Layout/IndentationWidth:
#   Enabled: false

# Layout/ArgumentAlignment:
#   Enabled: true
#   EnforcedStyle: with_fixed_indentation

# Lint/RaiseException:
#   Enabled: true

# Lint/StructNewOverride:
#   Enabled: true

# Metrics/MethodLength:
#   Max: 15

# Naming/AccessorMethodName:
#   Enabled: false

# Style/ConditionalAssignment:
#   Enabled: false
